---
url: localhost:3301
logs: ./logs.txt

handlers:
  go_handler:
    path: /go_handler
    file: handlers/go/handler.go

  cpp_handler:
    path: /cpp_handler
    file: handlers/cpp/handler.cpp
    build:
      tool: g++
      flags:
        - -static

  python_handler:
    path: /python_handler
    file: handlers/python/handler.py
    run:
      tool: python3

tasks:
  5_sec_periodic:
    file: tasks/5_sec_periodic.py
    period:
      cron: "* * * * * *"
    run:
      tool: python3
