---
url: localhost:3301
log: ./logs.txt
log_level: info

handlers:
  go_handler:
    path: /go_handler
    file: handlers/go/handler.go

  cpp_handler:
    path: /cpp_handler
    file: handlers/cpp/handler.cpp
    build:
      tool: g++
      flags:
        - -static

  python_handler:
    path: /python_handler
    file: handlers/python/handler.py
    run:
      tool: python3
  
  lua_handler:
    path: /lua_handler
    file: handlers/lua/handler.lua

tasks:
  5_sec_periodic:
    file: tasks/5_sec_periodic.py
    period: "*/5 * * * * *"
    run:
      tool: python3

  10_sec_periodic:
    file: tasks/10_sec_periodic.go
    period: "*/10 * * * * *"
